version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: '192.168.1.5.sslip.io'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://192.168.1.5.sslip.io'
        # Add any other gitlab.rb configuration here, each on its own line
      GITLAB_HOME: /srv/gitlab
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
